FROM inca.rte-france.com/farao/farao-computation-base-with-xpress:1.10.0
ARG JAR_FILE=rao-runner-app/target/*.jar
COPY ${JAR_FILE} app.jar
COPY .itools /home/farao/.itools

ENTRYPOINT ["java", "-jar", "/app.jar"]