version: '3'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    command: server /data