FROM inca.rte-france.com/farao/farao-computation-base-with-xpress:1.10.0 AS BUILDER
ARG JAR_FILE=rao-runner-app/target/*.jar
COPY ${JAR_FILE} app.jar
COPY .itools /home/farao/.itools
RUN mkdir -p /tmp/app  \
    && java -Djarmode=tools  \
    -jar /app.jar extract --layers --launcher \
    --destination /tmp/app

FROM inca.rte-france.com/farao/farao-computation-base-with-xpress:1.10.0
COPY .itools /home/farao/.itools
COPY --from=builder /tmp/app/dependencies/ ./
COPY --from=builder /tmp/app/spring-boot-loader/ ./
COPY --from=builder /tmp/app/application/ ./
COPY --from=builder /tmp/app/snapshot-dependencies/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]