spring:
  application:
    name: rao-runner-app
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    function:
      definition: stop

rao-runner:
  with-interruption-server: false
  messages:
    rao-request:
      queue-name: ${RAO_ADAPTER_SERVER_QUEUE_NAME:rao-request-queue}
      delivery-limit: 2
    rao-response:
      exchange: rao-response
      expiration: 600000 # (10x60s), time for applications to read the response
