spring:
  application:
    name: rao-runner-app
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    template:
      reply-timeout: 12000000

minio:
  bucket: ${MINIO_BUCKET:rao-integration-data}
  base-path: ${RAO_ADAPTER_SERVER_MINIO_BASE_PATH:default-base-path/}
  access:
    name: ${MINIO_USERNAME:minioadmin}
    secret: ${MINIO_PASSWORD:minioadmin}
  url: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}

rao-runner:
  messages:
    rao-request:
      queue-name: ${RAO_ADAPTER_SERVER_QUEUE_NAME:raoi-request-queue}
    rao-response:
      exchange: raoi-response
      expiration: 12000000
  url:
    whitelist:
      - http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
server:
  port: ${RAO_ADAPTER_SERVER_PORT:3030}